[mypy]
python_version = 3.10
files =
    amr/scripts/,
    scripts/,
    amr/pi5/ros2_ws/src/my_bot/my_bot/odom_to_tf.py
exclude = (?x)(
    my_bot/my_bot/(?!odom_to_tf\.py|__init__\.py)
    |\.venv
    |\.pio
    |node_modules
    |dashboard
    |build
    |install
    |log
  )

# Moderater Modus (<10% Type-Hints)
disallow_untyped_defs = false
check_untyped_defs = true
warn_no_return = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_unreachable = true
no_implicit_optional = true
namespace_packages = true
ignore_missing_imports = true

[mypy-rclpy.*]
ignore_missing_imports = true

[mypy-geometry_msgs.*]
ignore_missing_imports = true

[mypy-nav_msgs.*]
ignore_missing_imports = true

[mypy-sensor_msgs.*]
ignore_missing_imports = true

[mypy-std_msgs.*]
ignore_missing_imports = true

[mypy-tf2_ros.*]
ignore_missing_imports = true

[mypy-cv_bridge.*]
ignore_missing_imports = true

[mypy-cv2.*]
ignore_missing_imports = true

[mypy-websockets.*]
ignore_missing_imports = true

[mypy-google.*]
ignore_missing_imports = true

[mypy-hailort.*]
ignore_missing_imports = true

[mypy-numpy.*]
ignore_missing_imports = true

[mypy-matplotlib.*]
ignore_missing_imports = true

[mypy-launch.*]
ignore_missing_imports = true

[mypy-launch_ros.*]
ignore_missing_imports = true
