; ==========================================================================
; PlatformIO Configuration für AMR Sensor-Node (ESP32-S3 #2)
; ==========================================================================

[env]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino

build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -DARDUINO_USB_CDC_ON_BOOT=1
    -I include                      ; Lokaler Include-Ordner für config_sensors.h

monitor_speed = 115200
upload_speed = 921600

; Nutze den definierten udev-Symlink für den Sensor-Controller
upload_port = /dev/amr_sensor
monitor_port = /dev/amr_sensor

[env:sensor_node]
build_src_filter = +<*>

; --- micro-ROS Konfiguration ---
board_microros_transport = serial
board_microros_distro = humble

; --- Externe Bibliotheken ---
; micro-ROS + I2C-Geraete (IMU, Batterie, Servo)
lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio
    adafruit/Adafruit BusIO @ ^1.14.1
    adafruit/Adafruit INA260 Library @ ^1.5.0
    adafruit/Adafruit PWM Servo Driver Library @ ^3.0.2
    adafruit/Adafruit MPU6050 @ ^2.2.6
    adafruit/Adafruit Unified Sensor @ ^1.1.13
