[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = /dev/ttyACM0

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -I../../hardware

; micro-ROS Konfiguration
board_microros_transport = serial
board_microros_distro = humble

lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio
