#!/usr/bin/env bash
# Erzeugt aus der CAN-Signaldatenbank alle abgeleiteten Artefakte.
#
#   hardware/can-bus/amr_vehicle.dbc   (Quelle, handgepflegt)
#     -> amr/mcu_firmware/common/can/amr_vehicle.{h,c}   (C-Code fuer die ESP32-S3)
#     -> docs/architecture/can-signalkatalog.md          (Signalkatalog fuer MkDocs)
#
# Aufruf:
#   ./scripts/can_generate.sh           Artefakte neu erzeugen und schreiben
#   ./scripts/can_generate.sh --check   in ein temporaeres Verzeichnis erzeugen und
#                                       gegen den eingecheckten Stand vergleichen
#                                       (Rueckgabewert ungleich 0 bei Abweichung)
#
# Die erzeugten Dateien werden nicht handeditiert. Der Zeitstempel in der
# Kopfzeile des cantools-Generats wird entfernt, damit der Vergleich in
# Testfall T-09 (Schritt 5) reproduzierbar ist.
#
# Ausbaupaket K2, Phasenplan v2.1.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
dbc="${repo_root}/hardware/can-bus/amr_vehicle.dbc"
c_dir="${repo_root}/amr/mcu_firmware/common/can"
katalog="${repo_root}/docs/architecture/can-signalkatalog.md"

python_bin="${PYTHON:-${repo_root}/.venv/bin/python}"
if [[ ! -x "${python_bin}" ]]; then
    python_bin="$(command -v python3)"
fi

if ! "${python_bin}" -c "import cantools" 2>/dev/null; then
    echo "Fehler: cantools fehlt. Installation: .venv/bin/pip install -r requirements-dev.txt" >&2
    exit 2
fi

# Zeitstempel aus der cantools-Kopfzeile entfernen (reproduzierbarer Vergleich).
# -i mit angehaengter Endung verhaelt sich unter GNU-sed (Pi) und BSD-sed (macOS)
# gleich; "sed -i -E" deutet BSD-sed als Endung "-E" und scheitert am \1.
strip_timestamp() {
    sed -E -i.bak 's/(generated by cantools version [0-9A-Za-z.]+)[^.]*\./\1./' "$1"
    rm -f "$1.bak"
}

generate_c() {
    local out_dir="$1"
    mkdir -p "${out_dir}"
    "${python_bin}" -m cantools generate_c_source --output-directory "${out_dir}" "${dbc}" >/dev/null
    strip_timestamp "${out_dir}/amr_vehicle.h"
    strip_timestamp "${out_dir}/amr_vehicle.c"
}

mode="${1:-write}"

case "${mode}" in
    --check)
        tmp_dir="$(mktemp -d)"
        trap 'rm -rf "${tmp_dir}"' EXIT
        generate_c "${tmp_dir}/can"
        "${python_bin}" "${repo_root}/scripts/can_signalkatalog.py" \
            --dbc "${dbc}" --output "${tmp_dir}/can-signalkatalog.md"
        rc=0
        diff -u "${c_dir}/amr_vehicle.h" "${tmp_dir}/can/amr_vehicle.h" || rc=1
        diff -u "${c_dir}/amr_vehicle.c" "${tmp_dir}/can/amr_vehicle.c" || rc=1
        diff -u "${katalog}" "${tmp_dir}/can-signalkatalog.md" || rc=1
        if [[ ${rc} -eq 0 ]]; then
            echo "can_generate --check: erzeugte Artefakte stimmen mit dem eingecheckten Stand ueberein"
        else
            echo "can_generate --check: Abweichung gefunden, bitte ./scripts/can_generate.sh ausfuehren" >&2
        fi
        exit ${rc}
        ;;
    write)
        generate_c "${c_dir}"
        "${python_bin}" "${repo_root}/scripts/can_signalkatalog.py" \
            --dbc "${dbc}" --output "${katalog}"
        echo "erzeugt: ${c_dir}/amr_vehicle.{h,c}"
        echo "erzeugt: ${katalog}"
        ;;
    *)
        echo "Aufruf: $0 [--check]" >&2
        exit 2
        ;;
esac
